platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'WMobileKitExample' do
  pod 'WMobileKit', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'Material'
        config.build_settings['SWIFT_VERSION'] = '3.2'
      end
    end
  end
end
